---

vars:
  - &mgiAccessionUrl http://www.informatics.jax.org/accession/
  - &mousemineAccessionUrl http://www.mousemine.org/mousemine/portal.do?class=Gene&externalids=
  - &allianceAccessionUrl https://www.alliancegenome.org/gene/
  - &ensemblAccessionUrl http://www.ensembl.org/id/
  - &rgdAccessionUrl https://rgd.mcw.edu/rgdweb/report/gene/main.html?id=
  - &hgncAccessionUrl http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=
  - &zfinAccessionUrl https://zfin.org/
  - &fbAccessionUrl https://flybase.org/reports/
  - &wbAccessionUrl https://wormbase.org/species/c_elegans/gene/
  - &sgdAccessionUrl http://www.yeastgenome.org/locus/
  - &allianceSnapshotUrl https://fms.alliancegenome.org/api/snapshot/release/
  - &allianceDownloadUrl https://download.alliancegenome.org/

  - &mgiBuild38ModelsUrl http://www.informatics.jax.org/downloads/mgigff3/archive/annual/MGI.2021.gff3.gz
  - &mgiBuild39ModelsUrl http://www.informatics.jax.org/downloads/mgigff3/MGI.gff3.gz
  - &ncbiFtpBaseUrl ftp://ftp.ncbi.nlm.nih.gov/genomes/all/
  - &ensemblFtpBaseUrl ftp://ftp.ensembl.org/pub

  - &chr_re "^..?$"
  - &ensemblRelease "103"
  - &allianceRelease "4.0.0"

  - &transcriptChunkSize 4000000

linkConfigs:
  - &linkSgdByCid
    text: SGD
    url: *sgdAccessionUrl
    attr: cID
    stripPrefix: true

  - &linkWbByCid
    text: WormBase
    url: *wbAccessionUrl
    attr: cID
    stripPrefix: true

  - &linkFbByCid
    text: FlyBase
    url: *fbAccessionUrl
    attr: cID
    stripPrefix: true

  - &linkZfinByCid
    text: ZFIN
    url: *zfinAccessionUrl
    attr: cID
    stripPrefix: true

  - &linkHgncByCid
    text: HGNC
    url: *hgncAccessionUrl
    attr: cID

  - &linkMgiByID
    text: MGI
    url: *mgiAccessionUrl
    attr: ID

  - &linkMgiByCid
    text: MGI
    url: *mgiAccessionUrl
    attr: cID

  - &linkRgdByCid
    text: RGD
    url: *rgdAccessionUrl
    attr: cID
    stripPrefix: true

  - &linkMouseMineByID
    text: MouseMine
    url: *mousemineAccessionUrl
    attr: cID
    stripPrefix: true

  - &linkAllianceByCid
    text: Alliance
    url: *allianceAccessionUrl
    attr: cID

  - &linkEnsemblByID
    text: Ensembl
    url: *ensemblAccessionUrl
    attr: cID

assemblySources:
  - &ncbiAssembly
    source: ncbi
    baseUrl: *ncbiFtpBaseUrl
  - &ensemblAssembly
    source: ensembl
    release: *ensemblRelease
    baseUrl: *ensemblFtpBaseUrl

modelSources:
  - &ensemblMouseGff
    source: ensembl
    baseUrl: *ensemblFtpBaseUrl
    release: *ensemblRelease
    filters: [ ensemblMouseFilter ]
    exclude_types: ["biological_region", "chromosome", "scaffold"]
    chunkSize: *transcriptChunkSize
    linkouts:
      - *linkMgiByID
      - *linkMouseMineByID
      - *linkAllianceByCid
      - *linkEnsemblByID

  - &ensemblNonMouseGff
    source: ensembl
    baseUrl: *ensemblFtpBaseUrl
    release: *ensemblRelease
    filters: [ ensemblNonMouseFilter ]
    exclude_types: ["biological_region", "chromosome", "scaffold"]
    chunkSize: *transcriptChunkSize
    linkouts:
      - *linkAllianceByCid
      - *linkEnsemblByID

  - &allianceGff
    source: alliance
    release: *allianceRelease
    allianceDataType: GFF
    filters: [ allianceGff ]
    exclude_types: ["biological_region", "chromosome", "scaffold"]
    chunkSize: *transcriptChunkSize
    linkouts:
      - *linkAllianceByCid
    allianceSnapshotUrl: *allianceSnapshotUrl
    allianceDownloadUrl: *allianceDownloadUrl

buildList:
  -
    name: homologies
    orthologs:
      source: alliance
      release: *allianceRelease
      allianceDataType: ORTHOLOGY-ALLIANCE
      provider: COMBINED
      allianceSnapshotUrl: *allianceSnapshotUrl
      allianceDownloadUrl: *allianceDownloadUrl
  -
    name: mus_musculus_grcm39
    label: C57BL/6J (GRCm39)
    shortname: C57BL/6J
    build: GRCm38
    taxonid: "10090"
    chr_re: *chr_re
    assembly:
      << : *ensemblAssembly
      remotePath: mus_musculus
      source: ensembl
      release: "101"
      remotePath: "mus_musculus"
    models: 
      source: mgi
      filters: [ mgiGff ]
      release: "@@today"
      chunkSize: *transcriptChunkSize
      url: *mgiBuild39ModelsUrl
      linkouts:
        - *linkMgiByCid
        - *linkMouseMineByID
        - *linkAllianceByCid
  -
    name: mus_musculus_grcm38
    label: C57BL/6J (GRCm38)
    build: GRCm38
    taxonid: "10090"
    chr_re: *chr_re
    assembly:
      source: ensembl
      release: "101"
      remotePath: "mus_musculus"
    models: 
      source: mgi
      filters: [ mgiGff ]
      release: "4 Jan 2021"
      chunkSize: *transcriptChunkSize
      url: *mgiBuild38ModelsUrl
      linkouts:
        - *linkMgiByCid
        - *linkMouseMineByID
        - *linkAllianceByCid
  -
    name: mus_musculus_129s1svimj
    label: 129S1/SvImJ
    build: 129S1_SvImJ_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_aj
    label: A/J
    build: A_J_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_akrj
    label: AKR/J
    build: AKR_J_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_balbcj
    label: BALB/cJ
    build: BALB_cJ_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_c3hhej
    label: C3H/HeJ
    build: C3H_HeJ_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_c57bl6nj
    label: C57BL/6NJ
    build: C57BL_6NJ_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_caroli
    label: CAROLI/EiJ
    build: CAROLI_EIJ_v1.1
    taxonid: "10089"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_casteij
    label: CAST/EiJ
    build: CAST_EiJ_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_cbaj
    label: CBA/J
    build: CBA_J_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_dba2j
    label: DBA/2J
    build: DBA_2J_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_fvbnj
    label: FVB/NJ
    build: FVB_NJ_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_lpj
    label: LP/J
    build: LP_J_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_nodshiltj
    label: NOD/ShiLtJ
    build: NOD_ShiLtJ_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_nzohlltj
    label: NZO/HlLtJ
    build: NZO_HlLtJ_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_pahari
    label: PAHARI/EiJ
    build: PAHARI_EIJ_v1.1
    taxonid: "10093"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_pwkphj
    label: PWK/PhJ
    build: PWK_PhJ_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_spretus
    label: SPRETUS/EiJ
    build: SPRET_EiJ_v1
    taxonid: "10096"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: mus_musculus_wsbeij
    label: WSB/EiJ
    build: WSB_EiJ_v1
    taxonid: "10090"
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: *ensemblMouseGff
  -
    name: homo_sapiens
    label: H. sapiens
    taxonid: "9606"
    build: GRCh38
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: 
      << : *allianceGff
      provider: HUMAN
      filters: [ rgdGff ]
      linkouts:
        - *linkHgncByCid
        - *linkAllianceByCid
  -
    name: rattus_norvegicus
    label: R. norvegicus
    taxonid: "10116"
    build: Rnor_6.0
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: 
      << : *allianceGff
      provider: RGD
      filters: [ rgdGff ]
      linkouts:
        - *linkRgdByCid
        - *linkAllianceByCid
  -
    name: danio_rerio
    label: D. rerio
    taxonid: "7955"
    build: GRCz11
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: 
      << : *allianceGff
      provider: ZFIN
      filters: [ zfinGff ]
      linkouts:
        - *linkZfinByCid
        - *linkAllianceByCid
  -
    name: drosophila_melanogaster
    label: D. melanogaster
    taxonid: "7227"
    build: BDGP6.32
    chr_re: *chr_re
    assembly: *ensemblAssembly
    models: 
      << : *allianceGff
      provider: FB
      filters: [ flybaseGff ]
      linkouts:
        - *linkFbByCid
        - *linkAllianceByCid
  -
    name: caenorhabditis_elegans
    label: C. elegans
    taxonid: "6239"
    build: WBcel235
    chr_re: ".*"
    chr_sort: roman
    assembly: *ensemblAssembly
    models: 
      << : *allianceGff
      provider: WB
      chunkSize: 500000
      filters: [ wormbaseGff ]
      linkouts:
        - *linkWbByCid
        - *linkAllianceByCid
  -
    name: saccharomyces_cerevisiae
    label: S. cerevisiae
    taxonid: "559292"
    build: R64-1-1
    chr_re: ".*"
    chr_sort: roman
    assembly: *ensemblAssembly
    models: 
      << : *allianceGff
      provider: SGD
      filters: [ sgdGff ]
      linkouts:
        - *linkSgdByCid
        - *linkAllianceByCid
