
---

vars:
  - &mgiAccessionUrl http://www.informatics.jax.org/accession/
  - &mousemineAccessionUrl http://www.mousemine.org/mousemine/portal.do?class=Gene&externalids=
  - &allianceAccessionUrl https://www.alliancegenome.org/gene/
  - &ensemblAccessionUrl http://www.ensembl.org/id/
  - &rgdAccessionUrl https://rgd.mcw.edu/rgdweb/report/gene/main.html?id=
  - &hgncAccessionUrl http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=
  - &zfinAccessionUrl https://zfin.org/
  - &xenbaseAccessionUrl https://xenbase.org/entry/
  - &fbAccessionUrl https://flybase.org/reports/
  - &wbAccessionUrl https://wormbase.org/species/c_elegans/gene/
  - &sgdAccessionUrl http://www.yeastgenome.org/locus/
  - &allianceSnapshotUrl https://fms.alliancegenome.org/api/snapshot/release/
  - &allianceDownloadUrl https://download.alliancegenome.org/

  - &mgiBuild38ModelsUrl http://www.informatics.jax.org/downloads/mgigff3/archive/annual/MGI.2021.gff3.gz
  - &mgiCurrentModelsUrl http://www.informatics.jax.org/downloads/mgigff3/MGI.gff3.gz
  - &ncbiFtpBaseUrl ftp://ftp.ncbi.nlm.nih.gov/genomes/all/
  - &ensemblFtpBaseUrl ftp://ftp.ensembl.org/pub

  - &chr_re "^..?$"
  - &ensemblRelease "108"
  - &allianceRelease "5.4.0"

linkConfigs:
  - &linkSgdByCid
    text: SGD
    url: *sgdAccessionUrl
    attr: curie
    stripPrefix: true

  - &linkWbByCid
    text: WormBase
    url: *wbAccessionUrl
    attr: curie
    stripPrefix: true

  - &linkFbByCid
    text: FlyBase
    url: *fbAccessionUrl
    attr: curie
    stripPrefix: true

  - &linkZfinByCid
    text: ZFIN
    url: *zfinAccessionUrl
    attr: curie
    stripPrefix: true

  - &linkXenbaseByCid
    text: Xenbase
    url: *xenbaseAccessionUrl
    attr: curie
    stripPrefix: true

  - &linkHgncByCid
    text: HGNC
    url: *hgncAccessionUrl
    attr: curie

  - &linkMgiByID
    text: MGI
    url: *mgiAccessionUrl
    attr: ID

  - &linkMgiByCid
    text: MGI
    url: *mgiAccessionUrl
    attr: curie

  - &linkRgdByCid
    text: RGD
    url: *rgdAccessionUrl
    attr: curie
    stripPrefix: true

  - &linkMouseMineByID
    text: MouseMine
    url: *mousemineAccessionUrl
    attr: curie

  - &linkAllianceByCid
    text: Alliance
    url: *allianceAccessionUrl
    attr: curie

  - &linkEnsemblByID
    text: Ensembl
    url: *ensemblAccessionUrl
    attr: curie

assemblySources:
  - &ncbiAssembly
    source: ncbi
    track: assembly
    filetype: fasta
    baseUrl: *ncbiFtpBaseUrl
    chr_re: *chr_re
    filter: assemblyFilter
  - &ensemblAssembly
    source: ensembl
    track: assembly
    filetype: fasta
    release: *ensemblRelease
    baseUrl: *ensemblFtpBaseUrl
    chr_re: *chr_re
    filter: assemblyFilter

modelSources:
  - &ensemblMouseGff
    source: ensembl
    track: models
    chr_re: *chr_re
    filetype: gff
    baseUrl: *ensemblFtpBaseUrl
    release: *ensemblRelease
    filter: ensemblMouseFilter
    exclude_types: ["biological_region", "chromosome", "scaffold"]
    linkouts:
      - *linkMgiByID
      - *linkMouseMineByID
      - *linkAllianceByCid
      - *linkEnsemblByID

  - &ensemblNonMouseGff
    source: ensembl
    track: models
    filetype: gff
    chr_re: *chr_re
    baseUrl: *ensemblFtpBaseUrl
    release: *ensemblRelease
    filter: ensemblNonMouseFilter
    exclude_types: ["biological_region", "chromosome", "scaffold"]
    linkouts:
      - *linkAllianceByCid
      - *linkEnsemblByID

  - &allianceGff
    source: alliance
    track: models
    filetype: gff
    chr_re: *chr_re
    release: *allianceRelease
    allianceDataType: GFF
    filter: allianceGffFilter
    include_types: ["gene","mRNA","transcript","exon","CDS"]
    linkouts:
      - *linkAllianceByCid
    allianceSnapshotUrl: *allianceSnapshotUrl
    allianceDownloadUrl: *allianceDownloadUrl

buildList:
  -
    type: genome
    path: mus_musculus_grcm39
    name: C57BL/6J (GRCm39)
    shortname: C57BL/6J
    build: GRCm39
    taxonid: "10090"
    tracks:
      -
        << : *ensemblAssembly
        remotePath: mus_musculus
      -
        track: models 
        filetype: gff
        url: *mgiCurrentModelsUrl
        chr_re: *chr_re
        filter: mgiGffFilter
        release: "@@today"
        linkouts:
          - *linkMgiByCid
          - *linkMouseMineByID
          - *linkAllianceByCid
  -
    type: genome
    path: mus_musculus_grcm38
    name: C57BL/6J (GRCm38)
    build: GRCm38
    taxonid: "10090"
    tracks:
      -
        << : *ensemblAssembly
        release: "101"
        remotePath: "mus_musculus"
      -
        track: models
        source: mgi
        filetype: gff
        filter: mgiGffFilter
        chr_re: *chr_re
        release: "4 Jan 2021"
        url: *mgiBuild38ModelsUrl
        linkouts:
          - *linkMgiByCid
          - *linkMouseMineByID
          - *linkAllianceByCid
  -
    type: genome
    path: mus_musculus_129s1svimj
    name: 129S1/SvImJ
    build: 129S1_SvImJ_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_aj
    name: A/J
    build: A_J_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_akrj
    name: AKR/J
    build: AKR_J_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_balbcj
    name: BALB/cJ
    build: BALB_cJ_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_c3hhej
    name: C3H/HeJ
    build: C3H_HeJ_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_c57bl6nj
    name: C57BL/6NJ
    build: C57BL_6NJ_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_caroli
    name: CAROLI/EiJ
    build: CAROLI_EIJ_v1.1
    taxonid: "10089"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_casteij
    name: CAST/EiJ
    build: CAST_EiJ_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_cbaj
    name: CBA/J
    build: CBA_J_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_dba2j
    name: DBA/2J
    build: DBA_2J_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_fvbnj
    name: FVB/NJ
    build: FVB_NJ_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_lpj
    name: LP/J
    build: LP_J_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_nodshiltj
    name: NOD/ShiLtJ
    build: NOD_ShiLtJ_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_nzohlltj
    name: NZO/HlLtJ
    build: NZO_HlLtJ_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_pahari
    name: PAHARI/EiJ
    build: PAHARI_EIJ_v1.1
    taxonid: "10093"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_pwkphj
    name: PWK/PhJ
    build: PWK_PhJ_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_spretus
    name: SPRETUS/EiJ
    build: SPRET_EiJ_v1
    taxonid: "10096"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: mus_musculus_wsbeij
    name: WSB/EiJ
    build: WSB_EiJ_v1
    taxonid: "10090"
    tracks:
      - << : *ensemblAssembly
      - << : *ensemblMouseGff
  -
    type: genome
    path: homo_sapiens
    name: H. sapiens
    taxonid: "9606"
    build: GRCh38
    tracks:
      - << : *ensemblAssembly
      -
        << : *allianceGff
        provider: HUMAN
        filter: rgdGffFilter
        linkouts:
          - *linkHgncByCid
          - *linkAllianceByCid
  -
    type: genome
    path: rattus_norvegicus
    name: R. norvegicus
    taxonid: "10116"
    build: Rnor_6.0
    tracks:
      -
        << : *ensemblAssembly
        release: 104
      -
        << : *allianceGff
        provider: RGD
        filter: rgdGffFilter
        linkouts:
          - *linkRgdByCid
          - *linkAllianceByCid
  -
    type: genome
    path: danio_rerio
    name: D. rerio
    taxonid: "7955"
    build: GRCz11
    tracks:
      - << : *ensemblAssembly
      -
        << : *allianceGff
        provider: ZFIN
        filter: zfinGffFilter
        linkouts:
          - *linkZfinByCid
          - *linkAllianceByCid
  -
    type: genome
    path: xenopus_laevis_l
    name: X. laevis.L
    taxonid: "8355"
    build: GCA_017654675.1_Xenopus_laevis_v10.1
    tracks:
      - << : *ncbiAssembly
        chr_re: ".*"
        filter: ncbiFrogAssemblyFilter
      -
        << : *allianceGff
        provider: XBXL
        filter: xenbaseGffFilter
        chr_re: "^chr.*$"
        linkouts:
          - *linkXenbaseByCid
          - *linkAllianceByCid
  -
    type: genome
    path: xenopus_laevis_s
    name: X. laevis.S
    taxonid: "8355"
    build: GCA_017654675.1_Xenopus_laevis_v10.1
    tracks:
      - << : *ncbiAssembly
        chr_re: ".*"
        filter: ncbiFrogAssemblyFilter
      -
        << : *allianceGff
        provider: XBXL
        filter: xenbaseGffFilter
        chr_re: "^chr.*$"
        linkouts:
          - *linkXenbaseByCid
          - *linkAllianceByCid
  -
    type: genome
    path: xenopus_tropicalis
    name: X. tropicalis
    taxonid: "8364"
    build: UCB_Xtro_10.0
    tracks:
      - << : *ensemblAssembly
      -
        << : *allianceGff
        provider: XBXT
        filter: xenbaseGffFilter
        chr_re: "^Chr..?$"
        linkouts:
          - *linkXenbaseByCid
          - *linkAllianceByCid
  -
    type: genome
    path: drosophila_melanogaster
    name: D. melanogaster
    taxonid: "7227"
    build: BDGP6.32
    tracks:
      - << : *ensemblAssembly
      -
        << : *allianceGff
        provider: FB
        filter: flybaseGffFilter
        linkouts:
          - *linkFbByCid
          - *linkAllianceByCid
  -
    type: genome
    path: caenorhabditis_elegans
    name: C. elegans
    taxonid: "6239"
    build: WBcel235
    chr_sort: roman
    tracks:
      -
        << : *ensemblAssembly
        chr_re: ".*"
      -
        << : *allianceGff
        chr_re: ".*"
        provider: WB
        filter: wormbaseGffFilter
        linkouts:
          - *linkWbByCid
          - *linkAllianceByCid
  -
    type: genome
    path: saccharomyces_cerevisiae
    name: S. cerevisiae
    taxonid: "559292"
    build: R64-1-1
    chr_sort: roman
    tracks:
      -
        << : *ensemblAssembly
        chr_re: ".*"
      -
        << : *allianceGff
        chr_re: ".*"
        provider: SGD
        filter:  sgdGffFilter
        linkouts:
          - *linkSgdByCid
          - *linkAllianceByCid
  -
    type: homology
    path: homologies
    name: homologies
    tracks:
      -
        track: orthologs
        filetype: tsv
        source: alliance
        release: *allianceRelease
        allianceDataType: ORTHOLOGY-ALLIANCE
        provider: COMBINED
        allianceSnapshotUrl: *allianceSnapshotUrl
        allianceDownloadUrl: *allianceDownloadUrl
